### ISSUE TITLE
User-specified threshold / radius

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Attractors.jl#15]
I have some attractors. I have a feature of these attractors called "R". I want to cluster attractors by R, but with "threshold" 0.1, whatever this means. In principle I would like to separate attractors into clusters separated by distance 0.1.

To my understanding this could be done two ways in `ClusteringConfig` (please confirm if this is true)
1. initialize 0.1-spaced features and use them as templates. Then, choose `clustering_threshold = 0.1`. (?)
2. Use unsupervised method and specify the optimal radius to be 0.1. (???)

Number 2 isn't possible in current API. We should allow the user to provide a real number in `optimal_radius_method`, and then the search for optimal radius is skipped entirely and the provided value is used instead.

Would Number 1 as described do what I want?

P.s.: A bit off-topic but relevant. This is confusing:

>         clustering_threshold = 0.0: Maximum allowed
>         distance between a feature and the cluster center
>         for it to be considered inside the cluster. Only        
>         used when clust_method = "kNN_thresholded".

If the **maximum allowed distance** is by default 0, each point would become its own cluster, right? Because, by definition, each point will have **more than allowed distance** to be considered inside the cluster. In general the doc for this keyword is confusing and needs to be improved. cc @KalelR  Did you mean to make the deafult value for this `Inf` ?

**Comment by KalelR** [comment]
So many versions and algorithms, things start getting confusing! haha. Checking the code again, I noticed you are right,both the code and documentation could be much clearer. Some terminology I kept from the `bstab` paper implementation, which wasn't a good idea. I'll work on improving this to make everything clearer, I'll try to have a PR soon. The code as-is now should work though.
Idea No. 1 is to use templates, for which we'd use the `kNN` method, which works by assigning each feature to its nearest template (first neighbor). Each feature will be at a distance `d` to this nearest template. For perfect features and templates, this distance would always be zero, as each feature would be exactly on top of its nearest template. But it may be in practice that `d > 0`. If this distance `d > clustering_threshold`, meaning the feature's closest template is further than the allowed threshold, we say the feature does not belong to any template and assign the label `-1`. 

So for the "perfect case" `d = 0` only a `clustering_threshold <= 0 `makes the feature assigned to its template. So `clustering_threshold = 0` is a good default if we want to be very strict.  

> If the maximum allowed distance is by default 0, each point would become its own cluster, right? 
Not if several points are identical to the cluster, then all are assigned to that cluster. Otherwise yes. If for instance there's a small dispersion around the templates, the points would be labelled `-1`.

This method should work for what you want to do.


Number 2 wouldn't necessarily work. This is because the clustering method used in featurizing, dBSCAN, can group together points that are further away than the maximal radius. This is because the maximal radius is only used for the distance between pairs of points, so one can have a cluster with each point within the radius to another point, but not every point within that radius. For instance imagine the radius is `1`, one could have points 0.5, 1.0, 1.5, 2.0. 
So this algorithm might cluster `R` values more than `0.1` apart. Depends on how they are distributed.

**Comment by Datseris** [comment]
There is no such thing as perfect case. Like, even machine precision, that always goes into `mean`, would make things have distance >0, even 1e-16. I believe this 0 is not a good idea and we should have `Inf` as the default. A feature gets map to the closest template no matter how far away "closest" is.

**Comment by Datseris** [comment]
I am also confused on why you use `cluster_threshold <= 0`. We are talking distances, so negative numbers aren't on the table.

**Comment by Datseris** [comment]
For number 2: 

>  So this algorithm might cluster R values more than 0.1 apart. Depends on how they are distributed.

Yes, I understand that, but I am thinking that hte distributions of R values is multimodal with peaks separated _more_ than 0.1, so choosing 0.1, which would be something like 1/4 the width of each mode of the distribution, should be enough.

**Comment by KalelR** [comment]
> There is no such thing as perfect case. Like, even machine precision, that always goes into `mean`, would make things have distance >0, even 1e-16. I believe this 0 is not a good idea and we should have `Inf` as the default. A feature gets map to the closest template no matter how far away "closest" is.
> 
> EDIT: Only a user can meaningfully decide on a finite threshold as it depends on the dimensions / units of the data.

Good point. The code still works though because when `clustering_threshold = 0` we don't do the comparison. This is because we differentiated between `kNN` and `kNN_thresholded` which I think just doesn't make sense. I'm changing the code to update this, and I'll change the default value also. 

I mentioned `cluster_threshold <= 0` just for completeness, but of course any negative value wouldn't make sense.

**Comment by KalelR** [comment]
> For number 2:
> 
> > So this algorithm might cluster R values more than 0.1 apart. Depends on how they are distributed.
> 
> Yes, I understand that, but I am thinking that hte distributions of R values is multimodal with peaks separated _more_ than 0.1, so choosing 0.1, which would be something like 1/4 the width of each mode of the distribution, should be enough.

In that case then it should probably work. You can also limit the grouping of the features by increasing `min_neighbors` if necessary.
