### ISSUE TITLE
Unexpected `-1` label in `AttractorsViaFeaturizing`

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/Attractors.jl#3]
I've created some piece of code that allows for easy visualization and comparison of attractor finding between frameworks.

The code is here: https://gist.github.com/Datseris/f39147ab8ac68dd1231895f796b0f2dd

It just computes the trajectories for Lorenz84, and featurizes them with four different featurizers (see code). The results are here:

![lorenz84_clustering](https://user-images.githubusercontent.com/19669089/163715165-c879f931-9e9b-48d9-a8e8-d670eb4b26bd.png)

Colors purple, teal, and white, are valid attractors found by the algorithm. Color red is label -1. I do not understand why there is output -1, because I am not using the thresholded version, I am just using the default version.

cc @KalelR

**Comment by KalelR** [comment]
Hey, 

Featurizing seems to work fine on Lorenz84.  I can't run your code because there's missing info like the grid of ics but I created my own code using a regular grid we'd used before in Lorenz84 with default parameters of the clustering and the clustering works perfectly. As I remember, this problem occurred earlier under a different code version (maybe when the optimal silhouette was computed using the minimum value, not the average). But regardless it is not there now, as far as I see.

But just to be clear: the featurizing version can indeed return `-1` labels. This occurs if DBSCAN does not assign a cluster to the point, which occurs if its number of neighboring points is below `min_number_neighbors` (i.e. if the point is an outlier).

Figure:
![image](https://user-images.githubusercontent.com/38593444/197392715-d1120398-cc9d-4a53-b926-5fa342aca3ec.png)

Code:
```
using DynamicalSystems, OrdinaryDiffEq, Statistics, CairoMakie, Random
diffeq = (alg = Tsit5(), dt = 0.005, adaptive = false)

F = 6.886
G = 1.347
a = 0.255
b = 4.0

p = @ntuple F G a b
ds = Systems.lorenz84(; p...)

function feat1(A, t)
    x = A[:, 1]
    [minimum(x), std(x)]
end
function feat2(A, t)
    x, y, z = columns(A)
    [std(x), std(y)*std(z)]
end
function feat3(A, t)
    # g = exp(genentropy(A, 0.1; q = 0))
    probs = probabilities(A, RectangularBinning(0.1))
    g = exp(entropy(Renyi(0), probs))
    x = minimum(A[:,1])
    return [g,x]
end
function feat4(A, t)
    # g = exp(genentropy(A, 0.1; q = 0))
    probs = probabilities(A, RectangularBinning(0.1))
    g = exp(entropy(Renyi(0), probs))
    p = estimate_period(A[:,1], :zc)
    p = isnan(p) ? 0 : p
    return [g,p]
end

feats = [feat1 feat2; feat3 feat4]
labels = [("min(x)", "std(x)"),
    ("box cov.", "min(x)"),  ("std(x)", "std(y)*std(z)"), ("box cov.", "period")]
labels = reshape(labels, (2,2))


M = 200; z = 3; xg = yg = zg = range(-z, z; length = M); grid = (xg, yg, zg)
sampler, = statespace_sampler(Random.MersenneTwister(1234); min_bounds = minimum.(grid), max_bounds = maximum.(grid))
N = 1000;
ics = Dataset([sampler() for i in 1:N])
Ttr = 1000; #Ttr = 100 is not enough, there are some clear outlier features that disappear with Ttr=1000.

colors = [:purple, :black, :cyan, :red]
fig = Figure();
axs = [Axis(fig[i,j]; xlabel = labels[i,j][1], ylabel = labels[i,j][2]) for i in 1:2, j in 1:2];
clusterspecs = ClusteringConfig();
for i=1:2, j=1:2
    featurizer = feats[i,j]
    mapper = AttractorsViaFeaturizing(ds, featurizer, clusterspecs; diffeq, Ttr)
    feature_array = ChaosTools.extract_features(mapper, ics; show_progress=false, N)
    class_labels  = ChaosTools.cluster_features(feature_array, mapper.cluster_config)

    strokecolor = [colors[c == -1 ? 4 : c] for c in class_labels]
    outliers = findall(x->x==-1, class_labels)
    println(length(outliers))
    features = reduce(hcat, feature_array)
    scatter!(axs[i,j], features; markersize = 10, color = :transparent, strokecolor, strokewidth = 4)
end
Label(fig[0,1:2], "Lorenz 84, $N ics, Ttr = $Ttr")
fig
```

**Comment by Datseris** [comment]
Thanks Kalel, yes this was a remnant. I was running it with much older version, and I've ported the issue here for consistency.

**Comment by KalelR** [comment]
Sure :)
